### ISSUE TITLE
unable to get any response

### ISSUE THREAD

**Issue by mhdaslam790** [imtheguna/facebook_video_download#1]
Restarted application in 2,151ms.
I/flutter` ( 9927): [InstaData][storyFromUrl]: RangeError: Value not in range: 13
E/flutter ( 9927): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9927): #0      new FacebookPost.fromMap (package:facebook_video_download/data/facebookPost.dart:37:52)
E/flutter ( 9927): #1      FacebookData.postFromUrl (package:facebook_video_download/data/facebookData.dart:86:25)
E/flutter ( 9927): <asynchronous suspension>
E/flutter ( 9927): #2      _screenState.networking (package:flutter_app/screen.dart:58:27)
E/flutter ( 9927): <asynchronous suspension>
E/flutter ( 9927):

i am trying to get video url but getting this error

**Comment by AdilElhaci** [comment]
did you fix this issue ?

**Comment by mhdaslam790** [comment]
> did you fix this issue ?

Nop no luck..

**Comment by imtheguna** [comment]
Sorry guys, Now it support few videos only. looking it
